pub const TRANSFORM_OPCODE_PROJECT_UNIQUE_SCALAR: u8 = 1;
pub const TRANSFORM_OPCODE_COUNT_COLLECTION: u8 = 2;
pub const TRANSFORM_OPCODE_PROJECT_STATUS: u8 = 3;
pub const TRANSFORM_OPCODE_FILTER_REQUEST_VALUE: u8 = 4;

pub const TRANSFORM_VALUE_STRING: u16 = 0;
pub const TRANSFORM_VALUE_INTEGER: u16 = 1;
pub const TRANSFORM_VALUE_BOOLEAN: u16 = 2;
pub const TRANSFORM_VALUE_IDENTIFIER: u16 = 3;
pub const TRANSFORM_VALUE_COLLECTION: u16 = 5;

pub const TRANSFORM_FLAG_CANONICAL_JSON: u16 = 1;
pub const TRANSFORM_STATUS_ZERO_IS_SUCCESS: u16 = 0;
pub const TRANSFORM_STATUS_ZERO_IS_PASS: u16 = 1;
pub const TRANSFORM_STATUS_ZERO_IS_OK: u16 = 2;
pub const TRANSFORM_STATUS_ZERO_IS_TRUE: u16 = 3;
pub const TRANSFORM_ROLE_NONE: u8 = u8::MAX;

pub const OPERATOR_RENDERER_VERSION: u8 = 1;
pub const OPERATOR_RENDERER_STATIC: u8 = 1;
pub const OPERATOR_RENDERER_VALUE: u8 = 2;
pub const OPERATOR_RENDERER_TYPED_ACTOR: u8 = 3;
pub const OPERATOR_RENDERER_EMIT: u8 = 255;
